public enum OSSUARY_GROUPS
{
	LEFT_TOP = 0,
	LEFT_MIDDLE = 1,
	LEFT_BOTTOM_1 = 2,
	LEFT_BOTTOM_2 = 3,
	MIDDLE_TOP_LEFT = 5,
	MIDDLE_TOP_RIGHT = 6,
	MIDDLE_BOTTOM_LEFT = 7,
	MIDDLE_BOTTOM_RIGHT = 8,
	RIGHT_TOP = 9,
	RIGHT_MIDDLE = 10,
	RIGHT_BOTTOM_1 = 11,
	RIGHT_BOTTOM_2 = 12
}
