using ProtoBuf;

[ProtoContract(EnumPassthru = true)]
[UISortEnum(UISortEnumType.Alphabetical)]
[UICategorySort(CategorySortType.Appearance)]
public enum LocalizedVariableName
{
	[UICategory("Value")]
	Var,
	[UICategory("Value")]
	Count,
	[UICategory("Value")]
	Amount,
	[UICategory("Card")]
	Card,
	[UICategory("Card")]
	AbilityCard,
	[UICategory("Card")]
	Pile,
	[UICategory("Action")]
	Target,
	[UICategory("Value")]
	TargetCount,
	[UICategory("Action")]
	Damage,
	[UICategory("Action")]
	Draw,
	[UICategory("Action")]
	Heal,
	[UICategory("Card")]
	Hand,
	[UICategory("Action")]
	Offense,
	[UICategory("Action")]
	Defense,
	[UICategory("Action")]
	Attack,
	[UICategory("Grammar")]
	After,
	[UICategory("Action")]
	Health,
	[UICategory("Action")]
	Shield,
	[UICategory("Value")]
	CardValue,
	[UICategory("Card")]
	Color,
	[UICategory("Action")]
	Status,
	[UICategory("Action")]
	Action,
	[UICategory("Value")]
	ActionAmount,
	[UICategory("Grammar")]
	Name,
	[UICategory("Grammar")]
	Description,
	[UICategory("Action")]
	Class,
	[UICategory("Action")]
	Wild,
	[UICategory("Action")]
	WildRange,
	[UICategory("Action")]
	WildSuit,
	[UICategory("Value")]
	Var2,
	[UICategory("Value")]
	Var3,
	[UICategory("Value")]
	Var4,
	[UICategory("Value")]
	Var5,
	[UICategory("Action")]
	Ability,
	[UICategory("Action")]
	Enemy,
	[UICategory("Action")]
	Player,
	[UICategory("Action")]
	Summon,
	[UICategory("Action")]
	Redraw,
	[UICategory("Action")]
	Discard,
	[UICategory("Action")]
	Remove,
	[UICategory("Action")]
	Copy,
	[UICategory("Action")]
	Create,
	[UICategory("Action")]
	AttackDamage,
	[UICategory("Card")]
	DrawCard,
	[UICategory("Card")]
	DrawAbility,
	[UICategory("Card")]
	DiscardCard,
	[UICategory("Card")]
	DiscardAbility,
	[UICategory("Card")]
	CopyCard,
	[UICategory("Card")]
	CopyAbility,
	[UICategory("Action")]
	TargetEnemy,
	[UICategory("Action")]
	Level,
	[UICategory("Value")]
	AttackCost,
	[UICategory("Action")]
	GainAttack,
	[UICategory("Grammar")]
	AbilityName,
	[UICategory("Action")]
	ModDamage,
	[UICategory("Action")]
	ModAbilityDamage,
	[UICategory("Action")]
	ModAttackDamage,
	[UICategory("Time")]
	Time,
	[UICategory("Time")]
	Duration,
	[UICategory("Time")]
	TurnStart,
	[UICategory("Time")]
	TurnEnd,
	[UICategory("Time")]
	RoundEnd,
	[UICategory("Action")]
	Entity,
	[UICategory("Action")]
	Choice,
	[UICategory("Action")]
	Condition,
	[UICategory("Action")]
	HP,
	[UICategory("Action")]
	Ally,
	[UICategory("Action")]
	TopDeck,
	[UICategory("Card")]
	Suit,
	[UICategory("Card")]
	Spade,
	[UICategory("Card")]
	Club,
	[UICategory("Card")]
	Heart,
	[UICategory("Card")]
	Diamond,
	[UICategory("Action")]
	Opponent,
	[UICategory("Card")]
	AttackHand,
	[UICategory("Card")]
	DefenseHand,
	[UICategory("Action")]
	Attacker,
	[UICategory("Action")]
	Defender,
	[UICategory("Action")]
	TurnOrder,
	[UICategory("Time")]
	InCombat,
	[UICategory("Grammar")]
	Lower,
	[UICategory("Grammar")]
	Higher,
	[UICategory("Grammar")]
	Multi,
	[UICategory("Event")]
	SuccessfulAttack,
	[UICategory("Event")]
	SuccessfulDefense,
	[UICategory("Event")]
	FailedAttack,
	[UICategory("Event")]
	FailedDefense,
	[UICategory("Event")]
	UseAbility,
	[UICategory("Grammar")]
	Your,
	[UICategory("Grammar")]
	Their,
	[UICategory("Action")]
	CancelCombat,
	[UICategory("Action")]
	Tap,
	[UICategory("Time")]
	Encounter,
	[UICategory("Value")]
	Value,
	[UICategory("Card")]
	Red,
	[UICategory("Card")]
	Black,
	[UICategory("Event")]
	Defeat,
	[UICategory("Time")]
	Turn,
	[UICategory("Grammar")]
	Verb,
	[UICategory("Grammar")]
	Equal,
	[UICategory("Grammar")]
	Verb2,
	[UICategory("Grammar")]
	Verb3,
	[UICategory("Action")]
	AbilityDamage,
	[UICategory("Action")]
	MaxHealth,
	[UICategory("Grammar")]
	EnemyName,
	[UICategory("Action")]
	Trait,
	[UICategory("Card")]
	Pair,
	[UICategory("Grammar")]
	Deal,
	[UICategory("Time")]
	Round,
	[UICategory("Time")]
	Combat,
	[UICategory("Event")]
	Tie,
	[UICategory("Action")]
	Buff,
	[UICategory("Action")]
	Debuff,
	[UICategory("Value")]
	Number,
	[UICategory("Value")]
	AbilityCost,
	[UICategory("Card")]
	Deck,
	[UICategory("Action")]
	Move,
	[UICategory("Action")]
	Position,
	[UICategory("Action")]
	PreventHeal,
	[UICategory("Time")]
	Next,
	[UICategory("Value")]
	Random,
	[UICategory("Time")]
	First,
	[UICategory("Time")]
	UntilEndTurn
}
